# Generated by Django 6.0.3 on 2026-03-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FACTORY', 'Factory Expense'), ('OFFICE', 'Office Expense')], db_index=True, max_length=10, verbose_name='ประเภทแหล่งข้อมูล')),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ส่วนงาน')),
                ('dept_code', models.CharField(max_length=20, verbose_name='รหัสแผนก')),
                ('sub_dept_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัส (ย่อย)')),
                ('account_code', models.CharField(db_index=True, max_length=20, verbose_name='รหัสบัญชี')),
                ('account_name', models.CharField(max_length=255, verbose_name='รายการค่าใช้จ่าย')),
                ('period', models.CharField(blank=True, max_length=50, null=True, verbose_name='เดือน/ร.ป.')),
                ('expense_date', models.DateField(verbose_name='ว/ด/ป')),
                ('doc_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่เอกสาร/INV')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='SUP')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='จำนวนเงิน')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='VAT')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('external_id', models.CharField(blank=True, help_text='ID อ้างอิงจากไฟล์ต้นฉบับ', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รายการค่าใช้จ่าย',
                'verbose_name_plural': 'รายการค่าใช้จ่าย',
                'ordering': ['-expense_date', 'account_code'],
                'unique_together': {('source_type', 'account_code', 'expense_date', 'amount', 'doc_number')},
            },
        ),
    ]
