# Generated by Django 6.0.3 on 2026-03-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetransaction',
            name='sub_dept_code',
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='จำนวน'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='หน่วยนับ'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='doc_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่เอกสาร'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='expense_date',
            field=models.DateField(verbose_name='ว.ด.ป'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='เดือน/ปี'),
        ),
    ]
