# Generated by Django 6.0.3 on 2026-03-22 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rectyp', models.CharField(max_length=1, verbose_name='ประเภทเอกสาร')),
                ('docnum', models.CharField(max_length=20, unique=True, verbose_name='เลขที่เอกสาร')),
                ('docstat', models.CharField(blank=True, max_length=1, null=True, verbose_name='สถานะเอกสาร')),
                ('docdat', models.DateField(verbose_name='วันที่เอกสาร')),
                ('flgvat', models.CharField(blank=True, max_length=1, null=True, verbose_name='ประเภท VAT')),
                ('cusnam', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อลูกค้า (Joined)')),
                ('slmcod', models.CharField(blank=True, max_length=10, null=True, verbose_name='รหัสพนักงานขาย')),
                ('slmnam', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อพนักงานขาย (Joined)')),
                ('paytrm', models.IntegerField(default=0, verbose_name='เงื่อนไขการชำระ (วัน)')),
                ('duedat', models.DateField(blank=True, null=True, verbose_name='วันครบกำหนด')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ยอดรวม')),
                ('netamt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ยอดสุทธิ')),
                ('remamt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ยอดคงค้าง')),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รายการเคลื่อนไหวลูกหนี้',
                'verbose_name_plural': 'รายการเคลื่อนไหวลูกหนี้',
                'ordering': ['-docdat'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cuscod', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='รหัสลูกค้า')),
                ('cusnam', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อลูกค้า')),
                ('addr01', models.CharField(blank=True, max_length=200, null=True, verbose_name='ที่อยู่')),
                ('telnum', models.CharField(blank=True, max_length=50, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('crline', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='วงเงิน')),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ข้อมูลลูกค้า',
                'verbose_name_plural': 'ข้อมูลลูกค้า',
            },
        ),
        migrations.CreateModel(
            name='ReceiptCheck',
            fields=[
                ('rcp_num', models.CharField(max_length=20, verbose_name='เลขที่ใบเสร็จอ้างอิง')),
                ('cqnum', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='เลขที่เช็ค')),
                ('bankcod', models.CharField(max_length=10, verbose_name='รหัสธนาคาร')),
                ('chqdat', models.DateField(verbose_name='วันที่หน้าเช็ค')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ยอดเงินหน้าเช็ค')),
                ('stat', models.CharField(max_length=1, verbose_name='สถานะเช็ค')),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รายละเอียดเช็ครับ',
                'verbose_name_plural': 'รายละเอียดเช็ครับ',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docnum', models.CharField(max_length=20, verbose_name='เลขที่ใบเสร็จ')),
                ('docdat', models.DateField(verbose_name='วันที่รับชำระ')),
                ('invnum', models.CharField(max_length=20, verbose_name='เลขที่บิลที่อ้างถึง')),
                ('cutamt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ยอดที่ตัดจ่าย')),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='analytics.artransaction', to_field='docnum')),
            ],
            options={
                'verbose_name': 'รายละเอียดการรับชำระ',
                'verbose_name_plural': 'รายละเอียดการรับชำระ',
            },
        ),
    ]
